version: '3.8'

services:
  # PostgreSQL数据库
  postgres:
    image: ankane/pgvector
    container_name: postgres
    environment:
      POSTGRES_DB: hackathon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  # API Agent服务 (NestJS)
  agent-api:
    build:
      context: .
      dockerfile: apps/agent-api/Dockerfile
      target: development
    container_name: agent-api
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/hackathon
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
    depends_on:
      - postgres
      - redis
    develop:
      watch:
        - action: sync
          path: ./apps/agent-api/src
          target: /app/apps/agent-api/src
        - action: sync
          path: ./packages
          target: /app/packages
        - action: rebuild
          path: ./apps/agent-api/package.json
        - action: rebuild
          path: ./package.json

  # Web前端服务 (agent-web)
  agent-web:
    build:
      context: .
      dockerfile: apps/agent-web/Dockerfile
      target: development
    container_name: agent-web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - agent-api
    develop:
      watch:
        - action: sync
          path: ./apps/agent-web/src
          target: /app/apps/agent-web/src
        - action: sync
          path: ./packages
          target: /app/packages
        - action: rebuild
          path: ./apps/agent-web/package.json
        - action: rebuild
          path: ./package.json

volumes:
  postgres_data: